language: java
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec


language: java
deploy:
  edge: true
  provider: cloudfoundry  
  username: talk2jamesraj@yahoo.com
  password: sacsb4u!
  api: https://api.run.pivotal.io
  organization: letustry
  space: development
repo: https://github.com/Thamo/NewPhysicalInv.git